version: '3.8'

services:
  flask:
    build: ./yolov8
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8081:3000"
    depends_on:
      - flask
      
  mongodb:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data:
