version: "3"

services:
  yolov8:
    build: yolov8
    image: 127.0.0.1:30000/yolov8:v0.1
    ports:
    - "5000:80"

  frontend:
    build: frontend
    image: 127.0.0.1:30000/frontend:v0.1
    ports:
    - "8080:80"

  minio:
    image: minio/minio
    ports:
    - "9000:9000"
    - "9001:9001"
    environment:
      MINIO_ROOT_USER: zachminioadmin
      MINIO_ROOT_PASSWORD: zachminioadmin
    command: server /data --console-address ":9001"
    volumes:
    - minio_data:/data

volumes:
  minio_data:
    
